# This workflow build and push Docker image to docker hub
# https://docs.docker.com/ci-cd/github-actions/
name: dockerhub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to docker hub for Python 3.12
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          build-args: PYTHON_VERSION=3.12
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mamba:3.12
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline

      - name: Build and push to docker hub for Python 3.13
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          build-args: PYTHON_VERSION=3.13
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mamba:3.13,${{ secrets.DOCKER_HUB_USERNAME }}/mamba:latest
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
          platforms: |-
            linux/amd64
            linux/arm64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
